### ISSUE TITLE
Presentation of search results

### ISSUE THREAD

**Issue by nikja05** [nikja05/CineSearch#3]
Mit python im HTML automatisierte Liste erstellen, damit mehrere Resultate (z.B zehn auf einmal) angezeigt werden. 
In movie.html den Darstellungsblock in einen Python for loop stecken: `% for result in myresults: ` HTML template code `% end`.

**Comment by LeonHTM** [comment]
mir si dran

**Comment by LeonHTM** [comment]
fixed it
